### PR TITLE
Experimental - defui augments & devtools

### PR DESCRIPTION
**Pull request by Pancia**
```
;; can wrap an existing method
(defmethod aug/defui-augmentation :untangled.client.ui/DevTools
  [{:keys [defui/loc defui/ui-name env/cljs?]} ast _]
  (cond-> ast cljs?
    (aug/wrap-augment 'Object 'render
      (fn [[this] body]
        `(untangled.client.ui/wrap-render ~loc
           ~{:klass ui-name :this this}
           ~body)))))

;; can inject a (not already impl-ed) method/protocol
(defmethod aug/defui-augmentation :untangled.client.ui/DerefFactory
  [{:keys [defui/ui-name env/cljs?]} ast args]
  (aug/inject-augment ast 'static
    (if cljs? 'IDeref 'clojure.lang.IDeref)
    (if cljs? '-deref 'deref)
    `(fn [_#] (om.next/factory ~ui-name ~(or args {})))))

;; can define a grouping of augments 
;; (is fully recursive, ie can return other built-ins 
;;  and can return either the vector or the map #{:always :prod :dev} syntax)
(aug/add-defui-augmentation-group :untangled.client.ui/BuiltIns
  (fn [{:keys [aug params]}]
    '{:always [:untangled.client.ui/DevTools :untangled.client.ui/DerefFactory]}))
```

```
;; Usage in defui
(ui/defui ListItem [::ui/DevTools ::ui/DerefFactory]
  Object (render ....)

;; can parameterize augments
[(::ui/DerefFactory {:keyfn :value})]

;; group of augments
[::ui/BuiltIns] => [:untangled.client.ui/DevTools :untangled.client.ui/DerefFactory]
;; & can be parameterized
[(::ui/BuiltIns {::ui/DerefFactory {:keyfn :value}})]

;; can limit augments to dev/prod based on 
;; "DEFUI_AUGMENT_MODE" env var or system property
{:always [::ui/DevTools]
 :prod   [(::ui/WithExclamation {:excl "IN PROD MODE"})]
 :dev    [(::ui/WithExclamation {:excl "IN DEV MODE"})]}
```

### CODE REVIEW

**Comment by jasonjckn** [comment]
very happy to see this! keep up the great work!

**Comment by jasonjckn** [comment]
@Pancia i've been writing macros around defui, here's the code incase you find it helpful, i wrote it like I would write a compiler AST transformer

```
  (let [
        body-ast (s/conform ::specs/defui body)
        body-ast$ (defui-ast-transform body-ast)
        body$ (s/unform ::specs/defui body-ast$)
etc....

(def static-symbs #{"IQuery" "Ident" "InitialAppState"})
(defn defui-ast-transform [ast]
  (letfn [(walk-fn [xf]
            (-> xf
                (match->
                 {:protocol (_ :guard #(static-symbs (name %)))}
                 (assoc :static? 'static)

                 {:method-name 'getChildContext :args [this] :body body}
                 (assoc :body `[(cljs.core/js-obj
                                 "framework.core$ctx"
                                 (merge (framework.core/context ~(s/unform ::cs/binding-form this))
                                        (do ~@body)))])



                 {:method-name 'render :args [this om-props] :body body}
                 (assoc :args [this]
                        :body `[(let [~(s/unform ::cs/binding-form om-props)
                                      (framework.core/props ~(s/unform ::cs/binding-form this))]
                                  ~@body)])

                 :else (mu/*recur-walk*))))]
    (mu/walk-explicit-recur ast walk-fn)))
```

here's the implementation of helper parsing functions:

```
(ns framework.macro-utils
  (:require [clojure.core.match :refer [match]]
            [clojure.walk :refer [walk]]))

(defmacro match-> [x & clauses]
  {:pre [(even? (count clauses))]}
  (let [clauses-2 (partition 2 clauses)

        [last0 last1] (last clauses-2)

        clauses-2$ (concat clauses-2
                           (if (= last0 :else) []
                               [[:else `(identity)]]))
        s (gensym)]
    `(let [~s ~x]
       (match
        ~s
        ~@(apply concat
                 (for [[pattern action] clauses-2$]
                   [pattern
                    `(-> ~s
                         ~action)]))))))


(defn- speed-walk [afn m]
  (cond (map? m) (into (empty m) (for [[k v] m] [k (afn v)]))
        :else (walk afn identity m)))

(def ^:dynamic *recur-walk*)

(defn walk-explicit-recur [form afn]
  (binding [*recur-walk* (fn [form] (speed-walk afn form))]
    (afn form)))
```

**Comment by jasonjckn** [comment]
does intellij analysis still work if you have your own defui macro? I think it's hardcoded to only recognize om.next/defui

**Comment by Pancia** [comment]
Yeah my main ideas are
- Using spec as a way to define and ast and transformations on that ast
- Providing a hook for custom ast-xforms, so we aren't writing defui macros all the time, and have a way to use various ast-xforms from different places

My current thought process is that in your project you have to define your own defui macro, but then you can use whatever function transformations you want if you call out to untangled.client.ui/defui\* while passing it your desired list of ast-xforms.

**Comment by jasonjckn** [comment]
- "Providing a hook for custom ast-xforms" love this idea
- "My current thought process is that in your project you have to define your own defui macro, but then you can use whatever function transformations you want if you call out to untangled.client.ui/defui\* " thinking about my comment: "does intellij analysis still work if you have your own defui macro? I think it's hardcoded to only recognize om.next/defui" i think you may need to use alter-var-root on om.next/defui to continue with intellij recognition, or at least provide this as an option, i've done this I can send you the code if you want
- In my own code I already took control of defui, so I'm definitely glad you're not trying to take ownership of that macro in your devtools
- `(-> body s/conform ast-transform s/unform)` for the win

**Comment by jasonjckn** [comment]
be sure to test IDeref / factory function in advanced compilation
I had difficulty with it 2 months ago, haven't tested advanced mode since

also, would be nice to pick-and-choose what extension I want, similar to dirac features `[:hints :async ..etc]` would be `[:ideref :overlay ..etc ]`  following this train of thought I want certain extensions in dev mode `[:ideref :overlay]`, and others in production `[:ideref]`

**Comment by awkay** [comment]
Just to record our general results from our conversation about this. I was thinking we could define helpers like this:

```
(defwrapper WRAPPERNAME Object render ...a function that gets passed original render like ring middleware...)
(deftransform XFORMNAME Object render ...a function that gets passed the CODE of render and can morph it...)
...

(untangled/defui  Component  [DevToolRender CssRenderXForm]
   ... as before ...)
```

The idea is to have various kinds of things you can define sort of like mix-ins. They could affect lifecycle, add protocol implementation, etc. The trick is then you can apply them to a defui in a sequence (the vector arg of our proposed defui).

This would allow you to do things like add in macro-like classname transforms of render bodies (ala our CSS library), wrap render with real logic (e.g. dev tools functionality), etc.

More powerful than React mix-ins, but would allow you to create libraries of functions that can alter UI components in predictable ways. They compose, could have defined order (via the vector), can do macro-like or runtime function-like things.

**Pull request merged**
