### PR TITLE
    fix for issue #25, 2xload-field on the queue cause ::not-found for one of the fields

### PR DESCRIPTION
**Pull request by jasonjckn**
```
fix for issue #25, 2xload-field on the queue cause ::not-found for one of the fields
```

### CODE REVIEW

**Comment by awkay** [comment]
Hey. Looking this over I'm not sure it is general-purpose enough. It looks like you're only handling the "field" case where there is a join on an ident duplicate. There are other cases we need to cover for this to be right. 

Feel free to help me think through the cases. Composition of components should not really cause more than local loads to happen at once (other than the field case)...so perhaps it's ok.

**Comment by jasonjckn** [comment]
thanks for taking a look!

the most general description of this issue is: a single fetch-payload can never have a  subquery with >=2 keys. `(e.g. {:entitlements [:foo :bar]})` this query results in the backend parser being called twice (once per key in the subquery) (e.g. `{:entitlements [:foo]}` and `{:entitlements [:bar]}`.  client side doesn't merge the two calls properly, and ends up putting `::not-found` into app-state for one of the keys.

in this diff I try to detect the ident case which is a subset of the above, but i'm not sure how to address the general subquery case at the enqueue call site.

---

let's say you do the optimized version where if the Q contains 2 items with the same key, you merge the subquery, is it really that hard to get right?

consider my parser

```
(defmethod api-read :entitlements
  [{:keys [parser query] :as env} key params]
  {:value (parser env query)})

(defmethod api-read :ent-profile
  [env key {:keys [sso-id]}]
  {:value (auth/profile-by-id! sso-id)})

(defmethod api-read :ent-details
  [env key {:keys [sso-id]}]
  {:value (auth/entitlements-by-id! sso-id)})
```

 
the problem is my backend parser `api-read :entitlements` is called twice with 2 different queries, even though the client merged them, such that my LOG output on the backend is

```
16-08-17 23:49:31 fabric INFO [admin.system:21] - Read Request: [ :entitlements [(:ent-details {:sso-id "54d2497fe3e8d00800893017"})]] 
16-08-17 23:49:31 fabric INFO [admin.system:21] - Recursive Read Request: [ :ent-details  ] ({:sso-id "54d2497fe3e8d00800893017"})
16-08-17 23:49:45 fabric INFO [admin.system:21] - Read Request: [ :entitlements [(:ent-profile {:sso-id "54d2497fe3e8d00800893017"})]] 
16-08-17 23:49:45 fabric INFO [admin.system:21] - Recursive Read Request: [ :ent-profile  ] ({:sso-id "54d2497fe3e8d00800893017"})
```

The backend got 2 read requests even though the client ‘merged’ them. If instead we just have a single read request into `api-read :entitlements` in the backend, this would also fix the issue. Then the LOG output would be

```
16-08-17 23:49:31 fabric INFO [admin.system:21] - Read Request: [ :entitlements [(:ent-details {:sso-id "54d2497fe3e8d00800893017"})
                                                                              (:ent-profile {:sso-id "54d2497fe3e8d00800893017"})]] 
16-08-17 23:49:31 fabric INFO [admin.system:21] - Recursive Read Request: [ :ent-details  ] ({:sso-id "54d2497fe3e8d00800893017"})
16-08-17 23:49:45 fabric INFO [admin.system:21] - Recursive Read Request: [ :ent-profile  ] ({:sso-id "54d2497fe3e8d00800893017"})
```

there's a mismatch between server response and client request:

client's merged query:

```
 {:entitlements [:ent-details :ent-profile]}
```

should result in a single call to api-read, so that the returned payload matches with what was requested.

**Comment by awkay** [comment]
OK, if you look at the network request, you'll see that UC does NOT merge `[{:a [:x]}]` `[{a [:y]}]` as `[{:a [:x :y]}]` (as your text above implies), but instead (incorrectly) merges them as
 `[{:a [:x]} {:a [:y]}]` which cannot possibly work correctly (because the result is simply a map that has only one key (:a). This is why your server-side parser is called twice from the top level and makes a bad result `{:a {:y val}}` (which in turn causes `:x` to get set to not found).

There are two possible solutions: Do the merge correctly (hard, and still possible to cause errors) or split the two requests so that two separate network requests happen (easier, though a bit chatty). 

In the `load-field` case, the joins are auto-generated using the ident, so you get: `[{[:id 1] [:field-1]}]` and `[{[:id 1] [:field-2]}]`. The thing I'm trying to point out about your code is that I want to make sure you're understanding the problem, and what you're trying to split out. 

It is also possible for there to be multiple load-data calls that cause something like this `[:x :x :x]` (all of which technically could be collapsed).

However, this latter case won't cause a real error, just possibly extra work on the server.

So, the case to be fixed is always of the "join" form; however, you need to make sure you're using the entire "join key". The problem boils down to a pretty simple description:

For each network processing sequence:
- Scan the merged query.
- Props pass through  (you could keep track of the ones seen, to prevent dupes)
- Joins: The first instance of a join key is passed through to go with the current network request, any additional joins on the exact same key go back on the requests queue.

So, I'm reviewing your code to make sure it follows at least the full general case on joins.

**Comment by awkay** [comment]
I'd also like to see this particular part of the algorithm (the part that splits the items to load into "those to load now, and those to defer to later") into a pure function that can be properly behavioral tested, and I'd like to see a battery of clean behavioral cases showing that it works properly.

**Comment by jasonjckn** [comment]
@awkay PR is updated, added unit tests, using om/join-key

**Pull request merged**
